# This file was generated by GoReleaser. DO NOT EDIT.
cask "damping" do
  version "0.7.1"

  on_macos do
    on_intel do
      sha256 "23a1c10d943764d78a34740132923b73a396678c79eb3be99a665d148dc0a250"
      url "https://github.com/amplify-lab/damping/releases/download/v#{version}/damping_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1b1bbd02f90c209ff7beaf9c5e7236f34eec2d02fc3852dbe50b191687bb3b45"
      url "https://github.com/amplify-lab/damping/releases/download/v#{version}/damping_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "cc316087e1671e85907c69e393f8a75b433ecabc4a870d3374abd85645f2e994"
      url "https://github.com/amplify-lab/damping/releases/download/v#{version}/damping_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "86ca957c0e571d58a1350da763effff2ce752ec64568248a80dbee71f64eb579"
      url "https://github.com/amplify-lab/damping/releases/download/v#{version}/damping_#{version}_linux_arm64.tar.gz"
    end
  end

  name "damping"
  desc "One policy, one audit trail — across your terminal and your MCP servers."
  homepage "https://damping.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "damping"

  # No zap stanza required

end
