# This file was generated by GoReleaser. DO NOT EDIT.
cask "damping" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "aa2088f256be40ac848fbda734c12d1ba2d824378908bc904562057f3428d80e"
      url "https://github.com/amplify-lab/damping/releases/download/v#{version}/damping_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "20eee9d7f66651dd203b528d61c4074ea3b5f0b1ce72586461dd81866fdbe043"
      url "https://github.com/amplify-lab/damping/releases/download/v#{version}/damping_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d153107cb83c1d22d247f9f8fb4ee37022342faaadabfe3b866c4f8deef8e724"
      url "https://github.com/amplify-lab/damping/releases/download/v#{version}/damping_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "911298772e94fac45f9d76b067e80c900ae3f0c0edf00f894e9838a971cd5730"
      url "https://github.com/amplify-lab/damping/releases/download/v#{version}/damping_#{version}_linux_arm64.tar.gz"
    end
  end

  name "damping"
  desc "One policy, one audit trail — across your terminal and your MCP servers."
  homepage "https://damping.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "damping"

  # No zap stanza required

end
