# This file was generated by GoReleaser. DO NOT EDIT.
cask "damping" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "8382951452537fb2b5d1c6b44db3acebd56739072073202712a6bd873bc1b219"
      url "https://github.com/amplify-lab/damping/releases/download/v#{version}/damping_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b1dce8ed09392abfa9d2e15ca0c464479e12e69309cd4c6c4db4f359553957fd"
      url "https://github.com/amplify-lab/damping/releases/download/v#{version}/damping_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3fed1508347a380c26880594528d5d6746bd25ddddbf737899cdf8e88e95f21a"
      url "https://github.com/amplify-lab/damping/releases/download/v#{version}/damping_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "afbb89ddb8608dbf10fc938c0f446e2fbb9975de14a639c4db71014c4f460644"
      url "https://github.com/amplify-lab/damping/releases/download/v#{version}/damping_#{version}_linux_arm64.tar.gz"
    end
  end

  name "damping"
  desc "One policy, one audit trail — across your terminal and your MCP servers."
  homepage "https://damping.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "damping"

  # No zap stanza required

end
